### ISSUE TITLE
implement a Young Tableu. Aim for simplicity!

### ISSUE THREAD

**Issue by whoiscris** [whoiscris/algorithms_for_competitive_programming_library#2]
reference: https://lyle.smu.edu/~saad/courses/cse3358/ps5/problemset5sol.pdf

# TODO
- [x] flesh out private members, constructors.
- [x] add **insert** method. should create a 1x1 tableau if it is empty or add another row if current row is full.
- [x] add **get_min** method. should retrieve minimum element. This resides always in (0,0).
- [x] add **delete_min** method. Should retrieve and delete the minimum.
- [x] finish **YoungTableau(vector<int> V)**. should use insert method to insert elements of V into Y.
- [x] after testing the implementation, move testing code to test/ and change the .cpp to a .hpp.

**Comment by whoiscris** [comment]
- [x] flesh out private members, constructors.
- [ ] add **insert** method. should create a 1x1 tableau if it is empty or add another row if current row is full.
- [ ] add **get_min** method. should retrieve minimum element. This resides always in (0,0).
- [ ] add **delete_min** method. Should retrieve and delete the minimum.
- [ ] finish **YoungTableau(vector<int> V)**. should use insert method to insert elements of V into Y.
